

# This file was *autogenerated* from the file solve_real.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_20 = Integer(20); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_0p99 = RealNumber('0.99'); _sage_const_256 = Integer(256); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_29 = Integer(29); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16)
import re
import ast
import hashlib
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

from fpylll import IntegerMatrix, LLL, CVP

print("[*] Leyendo output.txt...")

txt = open("output.txt", "r").read()

p = Integer(re.search(r"p = (\d+)", txt).group(_sage_const_1 ))
pairs = ast.literal_eval(re.search(r"pairs = (\[.*?\])\nenc_flag", txt, re.S).group(_sage_const_1 ))
enc_flag = ast.literal_eval(re.search(r"enc_flag = (\(.*\))", txt, re.S).group(_sage_const_1 ))

m = _sage_const_20 
n = _sage_const_30 

print("[*] p bits:", p.nbits())
print("[*] pares:", len(pairs))

A = []
Y = []

for x, y in pairs:
    x = Integer(x)
    y = Integer(y)

    # eval_poly usa Horner:
    # c0*x^29 + c1*x^28 + ... + c29
    row = [pow(x, n - _sage_const_1  - j, p) for j in range(n)]
    A.append(row)
    Y.append(y)

print("[*] Haciendo RREF modular...")

# RREF manual sobre GF(p)
M = [[Integer(A[i][j] % p) for j in range(n)] + [Integer(Y[i] % p)] for i in range(m)]

pivots = []
r = _sage_const_0 

for c in range(n):
    pivot = None
    for i in range(r, m):
        if M[i][c] % p != _sage_const_0 :
            pivot = i
            break

    if pivot is None:
        continue

    M[r], M[pivot] = M[pivot], M[r]

    inv_piv = inverse_mod(M[r][c], p)
    M[r] = [(v * inv_piv) % p for v in M[r]]

    for i in range(m):
        if i != r and M[i][c] % p != _sage_const_0 :
            factor = M[i][c] % p
            M[i] = [(M[i][j] - factor * M[r][j]) % p for j in range(n + _sage_const_1 )]

    pivots.append(c)
    r += _sage_const_1 

    if r == m:
        break

print("[*] rango:", r)

free = [j for j in range(n) if j not in pivots]
print("[*] variables libres:", len(free))

# Solución particular con libres = 0
sol = [Integer(_sage_const_0 )] * n
for row, c in enumerate(pivots):
    sol[c] = Integer(M[row][n] % p)

# Base del kernel modular
ker = []

for f in free:
    v = [Integer(_sage_const_0 )] * n
    v[f] = Integer(_sage_const_1 )

    for row, c in enumerate(pivots):
        v[c] = Integer((-M[row][f]) % p)

    ker.append(v)

def center(a):
    a = Integer(a % p)
    if a > p // _sage_const_2 :
        return a - p
    return a

print("[*] Montando lattice de la coset...")

rows = []

# p * I permite cambiar representantes mod p
for i in range(n):
    row = [Integer(_sage_const_0 )] * n
    row[i] = p
    rows.append(row)

# kernel modular
for v in ker:
    rows.append([center(x) for x in v])

B0 = IntegerMatrix(len(rows), n)

for i, row in enumerate(rows):
    for j, val in enumerate(row):
        B0[i, j] = int(val)

print("[*] LLL inicial...")
LLL.reduction(B0, delta=_sage_const_0p99 )

# Tomamos 30 filas no nulas después de LLL.
basis_rows = []
for i in range(B0.nrows):
    row = [Integer(B0[i, j]) for j in range(n)]
    if any(row):
        basis_rows.append(row)
    if len(basis_rows) == n:
        break

if len(basis_rows) != n:
    print("[-] No pude extraer base completa.")
    exit()

B = IntegerMatrix(n, n)

for i, row in enumerate(basis_rows):
    for j, val in enumerate(row):
        B[i, j] = int(val)

print("[*] LLL final...")
LLL.reduction(B, delta=_sage_const_0p99 )

target = [-center(x) for x in sol]

print("[*] CVP: buscando el vector de coeficientes pequeño...")
cv = CVP.closest_vector(B, [int(x) for x in target])

coeffs = [center(sol[i]) + Integer(cv[i]) for i in range(n)]

print("[*] Máximo tamaño encontrado:", max(abs(c).nbits() for c in coeffs), "bits")

# Verificación modular
for i in range(m):
    lhs = sum((A[i][j] * (coeffs[j] % p)) % p for j in range(n)) % p
    assert lhs == Y[i] % p

print("[+] Coeficientes verifican todos los pares.")

if not all(_sage_const_0  <= c < _sage_const_2 **_sage_const_256  for c in coeffs):
    print("[-] Los coeficientes no están todos en rango 0..2^256.")
    print("[*] Primeros coeficientes:", coeffs[:_sage_const_5 ])
    exit()

# Verificar la cadena SHA:
# coeffs[0] = MASTER_KEY como entero
# coeffs[i+1] = sha256(long_to_bytes(coeffs[i]))
def long_to_bytes_sage(x):
    x = int(x)
    if x == _sage_const_0 :
        return b"\x00"
    return x.to_bytes((x.bit_length() + _sage_const_7 ) // _sage_const_8 , "big")

test = [coeffs[_sage_const_0 ]]

for _ in range(_sage_const_29 ):
    h = hashlib.sha256(long_to_bytes_sage(test[-_sage_const_1 ])).digest()
    test.append(Integer(int.from_bytes(h, "big")))

if test != coeffs:
    print("[-] La cadena SHA no coincide. Vector incorrecto.")
    exit()

print("[+] Cadena SHA correcta.")

key = int(coeffs[_sage_const_0 ]).to_bytes(_sage_const_32 , "big")
iv = bytes.fromhex(enc_flag[_sage_const_0 ])
ct = bytes.fromhex(enc_flag[_sage_const_1 ])

pt = unpad(AES.new(key, AES.MODE_CBC, iv).decrypt(ct), _sage_const_16 )

print("[+] FLAG:", pt.decode())

